"""training change

Revision ID: 29c6b33e550c
Revises: ea47e4ecece9
Create Date: 2020-12-30 00:42:00.195576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29c6b33e550c'
down_revision = 'ea47e4ecece9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training', 'hour')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training', sa.Column('hour', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
