"""add Swimming

Revision ID: 5102bb535dc8
Revises: 63aeded7fa8c
Create Date: 2021-01-20 17:17:28.189253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5102bb535dc8'
down_revision = '63aeded7fa8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('swimming',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warm_up', sa.PickleType(), nullable=True),
    sa.Column('workout', sa.PickleType(), nullable=True),
    sa.Column('cool_down', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('swimming')
    # ### end Alembic commands ###
