"""change Swimming

Revision ID: 77dc4ee5bd25
Revises: 5102bb535dc8
Create Date: 2021-01-20 18:25:57.881187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77dc4ee5bd25'
down_revision = '5102bb535dc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('swimming', sa.Column('train_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('swimming', 'train_type')
    # ### end Alembic commands ###
