"""change Events

Revision ID: 7af5c8e0fd36
Revises: a546eabe4dc4
Create Date: 2021-01-20 19:23:12.049563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7af5c8e0fd36'
down_revision = 'a546eabe4dc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'name')
    # ### end Alembic commands ###
